name: Running Tests

on: [push]

permissions:
  checks: write
  contents: read

jobs:
  Test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres

        env:
          POSTGRES_PASSWORD: mypass
          POSTGRES_USER: myuser
          POSTGRES_DB: example

        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - run: |
          sudo apt-get update && sudo apt-get install --yes --no-install-recommends postgresql-client
      - run: |
          psql -h localhost -U myuser -d example -c 'create table categories (id bigserial primary key, avatar varchar not null, title varchar not null unique); create table club (id bigserial primary key,title varchar not null,description varchar not null,image_url varchar,category_id int8 references categories(id)); create table child (id bigserial primary key,first_name varchar not null,last_name varchar not null,birth_date date);create table club_child(club_id int8 references club(id),child_id int8 references child(id));'
        env:
          PGPASSWORD: mypass
      - uses: actions/checkout@v4
      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'
          cache: 'maven'
      - name: Test with Maven
        run: mvn clean test         

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()   
        with:
          name: Tests      
          path: '**/target/surefire-reports/TEST-*.xml'
          reporter: java-junit  
